<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="C40LAP-12601" failures="0" tests="1" name="LendistryLending.TC001_LL_InviteToPortal" time="412.942" errors="1" timestamp="2022-07-12T12:04:23 IST" skipped="0">
  <testcase classname="LendistryLending.TC001_LL_InviteToPortal" name="testB" time="412.942">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at com.Automation.Driver.DriverScript.executeKeywords(DriverScript.java:55)
at LendistryLending.TC001_LL_InviteToPortal.testB(TC001_LL_InviteToPortal.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.framework.exception.FrameworkException: ERROR: please check locator: //*[contains(text(),'Thank you for applying for a loan from Lendistry.')]
at com.Automation.Keywords.GenericKeywords.drawBorder(GenericKeywords.java:2115)
at com.Automation.Keywords.GenericKeywords.reportFailure(GenericKeywords.java:1951)
at com.Automation.Keywords.GenericKeywords.assertEqual(GenericKeywords.java:1513)
at com.Automation.Keywords.GenericKeywords.assertEqual(GenericKeywords.java:1509)
at com.Automation.Keywords.GenericKeywords.assertEqual(GenericKeywords.java:1509)
at com.Automation.Keywords.GenericKeywords.assertEqual(GenericKeywords.java:1509)
at com.Automation.Keywords.GenericKeywords.assertEqual(GenericKeywords.java:1509)
... 34 more
]]>
    </error>
  </testcase> <!-- testB -->
  <system-out/>
</testsuite> <!-- LendistryLending.TC001_LL_InviteToPortal -->
